FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build:prod

FROM nginx:alpine

COPY --from=build /app/dist/consultacredito /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 4040

CMD ["nginx", "-g", "daemon off;"]